language: java

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

# Remove lock files before caching
before_cache:
  - rm -f  $HOME/.gradle/caches/*/*.lock

# Cache only relevant directories
cache:
  directories:
    - $HOME/.gradle/caches/modules-2
    - $HOME/.gradle/wrapper/dists

install:
  - ./gradlew --version # Display Gradle, Groovy, JVM and other versions

jdk:
  - openjdk11
  - openjdk12
  - openjdk-ea

os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      jdk: openjdk12
    - os: osx
      jdk: openjdk-ea
  allow_failures:
    - jdk: openjdk-ea

script:
  - ./gradlew --scan --warning-mode=all -Dplatform.tooling.support.tests.enabled=true build

stages:
  - test
  - name: deploy
    if: repo = junit-team/junit5 AND (branch = master OR branch =~ /^releases\/\d+\.\d+\.x$/) AND type = push

notifications:
  slack:
    on_pull_requests: false
    rooms:
      - secure: WFsU02gopb070NzuGL97y83Oke8X18iyv93V1ZOjRDom1hiWtsiW0bA7VSGPXfAK2gjexhpmvmi8k97B92qkM5I8N3fERddu6YfxN4bXemXnvJuwUufN6fX/thO8+Wh4Qc5iPMRrnmYplDz9J5WzMLgNjs8WKQOwml418nRQmLs=
